<HTML>
<HEAD>
<TITLE>ChinaRen 网站数据分析</TITLE>
#include "style.css"
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000" LINK="#800080" VLINK="#0000A0" ALINK="#800000">
<!---->
#include "hash.phtml"
<!---->
#include "header.inc" 
<!---->

<center>
<table width=620 >
</table>
<center><h1>报告 BUG to: <font color=red><a href='mailto:zixia@chinaren-inc.com'>zixia@chinaren-inc.com</a></font></h1></center>
<br>
<table width=620 >
  <tr> 
    <td height=60> 
#include "footer.inc" 
</td>
  </tr>
</table>
</center>
</BODY>
</HTML>
