<!-- user/day.phtml started -->
<?
my $sth ;
my $tomorrow ;
#$tomorrow = $day_day +1 ;

$sth = $dbh->prepare ( <<_SQL_ )  or die "prepare in day.phtml error!" ;
select HOUR(FROM_UNIXTIME(ctime)) as hour ,count(*) from UserInfo 
where ctime >= UNIX_TIMESTAMP('$day_year-$day_month-$day_day') and
ctime < UNIX_TIMESTAMP(DATE_ADD('$day_year-$day_month-$day_day',INTERVAL 1 DAY))
group by hour 
order by hour desc 
_SQL_

$sth->execute or die "execute error in day.phtml" ;

my $hour;
my %user_counter; 
my $all_users ;

$all_users = 0 ;

while ( ($hour,$tmp)=$sth->fetchrow_array )
{
	$user_counter{$hour} = $tmp ;
	$all_users += $user_counter{$hour} ;
}
$sth->finish ;
!>

<table border=0 dwcopytype="CopyTableRow" cellpadding="0" cellspacing="0">
  <tr> 
    <td> 
      <table border=1 cellspacing="0" cellpadding="0" bordercolor=606000>
        <tr> 
          <td> 
            <table bgcolor=f0f0e0 class=small width=620 cellspacing=0 cellpedding=0 border=0>
              <tr> 
                <td colspan=2 bgcolor=606000><i><b><font size=+1 color=ffe080>1. 
                  </font></b></i><font color=ffffff>日 注 册 用 户 每小 时 增 量 <font color=red>总共<?=$all_users!>人</font> 
                  ( <?=$day_year!> 年 <?=$day_month!> 月 <?=$day_day!> 日 )</font></td>
              </tr>


<!-- foreach started -->
<?
my $bgcolor='fffff8';
foreach $hour ( reverse sort {$a<=>$b} keys %user_counter )
{
!>
              <tr bgcolor=<?=$bgcolor!>> 
                <td align=right> <?=$hour!> 点: </td>
                <td><img src=/images/bar3.gif width=<?=int(1+($all_users==0?0:($bar_length*($user_counter{$hour}/$all_users))))!> height=7><font color=208000>
<?=$user_counter{$hour}!></font> <font
color=ff0000><?=substr($all_users==0?0:(100*$user_counter{$hour}/$all_users),0,4)!>%</font></td>
              </tr>
		<? if ($bgcolor eq 'fffff8'){
				$bgcolor='f0f0e0' ;
			}else{
				$bgcolor='fffff8' ;
			}
}
!>
<!-- foreach ended -->

            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<!-- user/day.phtml ended -->
