<!-- user/month.phtml started-->
<?
my $sth ;
my $next_month ;
#$next_month = $month_month + 1 ;


$sth = $dbh->prepare ( <<_SQL_ )  or die "prepare in day.phtml error!" ;
select DAYOFMONTH(FROM_UNIXTIME(ctime)) as day ,count(*) from UserInfo 
where ctime >= UNIX_TIMESTAMP('$month_year-$month_month-01') and 
ctime < UNIX_TIMESTAMP(DATE_ADD('$month_year-$month_month-01',INTERVAL 1 month)) 
group by day
order by day desc 
_SQL_

$sth->execute() or die "execute in month.phtml" ;

my $day;
my %user_counter; 
my $all_users ;

$all_users = 0 ;
while ( ($day,$tmp)=$sth->fetchrow_array )
{
	$user_counter{$day}=$tmp ;
	$all_users += $user_counter{$day} ;
}
$sth->finish ;
!>

<table border=1 cellspacing="0" cellpadding="0" bordercolor=606000 dwcopytype="CopyTableRow"><tr><td> 
	<table bgcolor=f0f0e0 class=small width=620 cellspacing=0 cellpedding=0 border=0>
	<tr>
		<td colspan=2 bgcolor=606000>
			<i><b><font size=+1 color=ffe080>
			2. </font></b></i>
			<font color=ffffff>月 注 册 用 户 每 天 增 量 
			<font color=red>总共<?=$all_users!>人</font>
			( <?=$month_year!> 年 <?=$month_month!> 月 )</font>
		</td>
	</tr>

<!-- foreach started -->
<?
my $bgcolor='fffff8';
foreach $day ( reverse sort {$a<=>$b} keys %user_counter )
{
!>
	<tr bgcolor=<?=$bgcolor!>> 
		<td align=right> <?=$day!> 日: </td>
		<td>
			<img src=/images/bar3.gif width=<?=int(1+($all_users==0?0:($bar_length*($user_counter{$day}/$all_users))))!> height=7>
			<font color=208000><?=$user_counter{$day}!></font> 
			<font color=ff0000><?=substr($all_users==0?0:(100*$user_counter{$day}/$all_users),0,4)!>%</font>
		</td>
	</tr>
		<? if ($bgcolor eq 'fffff8'){
				$bgcolor='f0f0e0' ;
			}else{
				$bgcolor='fffff8' ;
			}
}
!>
<!-- foreach ended -->
              </table>
</td> </tr></table>
<!-- user/month.phtml ended-->
