<!-- product/month.phtml started -->
<?
local (%page_view, %prod_page_view)  ;
#local ($product) ;

my ($sth,$date,$product,$all_pageview) ;
local $tmp ;

$sth = $dbh_log->prepare ( <<_SQL_ )  or die "prepare in product/month.phtml error!" ;
select DAYOFMONTH(date_hour) as day ,sum(num_chinaren) from pageview_tb 
where date_hour >= '$month_year-$day_month-01' and
date_hour < DATE_ADD('$month_year-$month_month-01',INTERVAL 1 MONTH)
group by day 
_SQL_

$all_pageview = 0 ;
$sth->execute or die "execute in product/month.phtml error!" ;
while ( ($date,$tmp)=$sth->fetchrow_array ){
	$page_view{$date}=$tmp ;
	$all_pageview += $tmp ;
}
$sth->finish ;

foreach $date ( reverse sort {$a<=>$b} keys %page_view ){
	$sth = $dbh_log->prepare ( <<_SQL_ )  or die "prepare in product/month.phtml error!" ;
select product ,sum(num_chinaren) from pageview_tb 
where date_hour >= '$month_year-$month_month-$date' and
date_hour < DATE_ADD('$month_year-$month_month-$date',INTERVAL 1 DAY)
group by product
_SQL_
	$sth->execute or die "execute group by host_name error in product/month.phtml" ;
	while ( ($product,$tmp)=$sth->fetchrow_array ){
		$prod_page_view{$date}{($Host2Name{$product})} = $tmp ;
	}
	$sth->finish ;
} 
!>

<table border=1 cellspacing="0" cellpadding="0" bordercolor=606000>
<tr><td> 

<table bgcolor=fff8e0 class=small width=620 cellspacing=0 cellpedding=0 border=2 bordercolor=606000>
<tr> 
    <td colspan=3 bgcolor=606000><I><B><font size=+1 color=ffe080>2. 
	    </font></B></I><font color=ffffff>
		月 产 品 PageView 分析
		<font color=red> 总PageView: <b>
	<?=(($remote_user=~/[logadm|all]/)?$all_pageview:'不详')!>
	</b> 页</font> ( <?=$month_year!>年<?=$month_month!>月 )</font>
	</td>
</tr>

<!-- foreach 1 started -->
<?
foreach $date ( reverse sort {$a<=>$b} keys %page_view )
{
!>
<tr bgcolor=fffff8> 
	<td align=right> <?=$date!> 日: </td>
    	<td> 
		<!-- table per date -->
            <table cellspacing=0 cellpadding=0 border=0 width=100%>
	<!-- foreach 2 started -->
	<? foreach $product ( reverse sort {$prod_page_view{$date}{$a}<=>$prod_page_view{$date}{$b}} keys %{$prod_page_view{$date}} ) { next if ( ( $use_filter && ($product ne $filter) ) ) ;!>
            <tr height=7>
                <td><img src="/images/bar3.gif" width="<?=int(1+($page_view{$date}==0?0:($bar_length*($prod_page_view{$date}{$product})/$page_view{$date})))!>" height="7" border=0><font size=2 color=208000> 
                  [<?=$product!>]<?=$prod_page_view{$date}{$product}!> 页</font> <font size=2 color=ff0000> <?=$page_view{$date}==0?0:substr(100*$prod_page_view{$date}{$product}/$page_view{$date},0,4)!>%</font></td>
             </tr>
	<? } !>
	<!-- foreach 2 ended -->
		<!-- table per date ended -->
          </td>
        </tr>
	</table>
</td></tr>
<?
}
!>
<!-- foreach 1 end -->

</table>

</td></tr>
</table>
<!-- product/month.phtml ended -->
